import { StyleSheet } from "react-native";
import theme from "../../../../../constants/theme";

const T = theme.lightMode;
export default StyleSheet.create({
    panel: {
        backgroundColor: T.cards.background,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 10,
    },
    handleContenedor: {
        alignItems: 'center',
        paddingVertical: 4,
        marginBottom: 8,
    },
    handle: {
        width: 40, height: 4,
        backgroundColor: '#e2e8f0',
        borderRadius: 2,
        marginTop: 10,
    },
    textoHint: {
        fontSize: 11,
        color: T.text.secondary,
        marginTop: 4,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    titulo: { fontSize: 17, fontWeight: '700', color: T.text.primary },
    subtitulo: { fontSize: 12, color: T.text.secondary, marginTop: 2 },
    botonCerrar: {
        padding: 4,
        backgroundColor: T.input.background,
        borderRadius: 20,
    },
    progresoContenedor: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    progresoItem: { flexDirection: 'row', alignItems: 'center' },
    progresoBurbuja: {
        width: 28, height: 28,
        borderRadius: 14,
        backgroundColor: T.input.background,
        borderWidth: 2,
        borderColor: '#e2e8f0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    progresoBurbujaActiva: { backgroundColor: '#22C55E', borderColor: '#22C55E' },
    progresoBurbujaCompletada: { backgroundColor: '#16a34a', borderColor: '#16a34a' },
    progresoNumero: { fontSize: 12, fontWeight: '700', color: '#94a3b8' },
    progresoLinea: { width: 40, height: 2, backgroundColor: '#e2e8f0', marginHorizontal: 4 },
    progresoLineaActiva: { backgroundColor: '#22C55E' },
    pasoContenedor: { marginBottom: 16 },
    input: {
        backgroundColor: T.input.background,
        borderColor: T.input.border,
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 12,
        color: T.input.text,
        fontSize: 14,
        marginBottom: 4,
    },
    inputError: {
        borderColor: '#ef4444',
        borderWidth: 1.5,
    },
    textoError: {
        fontSize: 11,
        color: '#ef4444',
        marginBottom: 8,
        marginLeft: 4,
    },
    selectorContenedor: {
        borderWidth: 1,
        borderColor: T.input.border,
        borderRadius: 10,
        backgroundColor: T.input.background,
        marginBottom: 4,
        overflow: 'hidden',
    },
    selectorError: {
        borderColor: '#ef4444',
        borderWidth: 1.5,
    },
    labelSeccion: {
        fontSize: 13,
        fontWeight: '600',
        color: T.text.primary,
        marginBottom: 6,
        marginTop: 4,
    },
    infoTrazado: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#f0fdf4',
        borderRadius: 8,
        padding: 10,
        marginBottom: 12,
    },
    textoInfoTrazado: { fontSize: 12, color: '#16a34a', flex: 1 },
    textoSinPuntos: { color: T.text.secondary, fontSize: 13, textAlign: 'center', paddingVertical: 12 },
    puntoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: T.cards.border,
    },
    puntoBurbuja: {
        width: 22, height: 22,
        borderRadius: 11,
        backgroundColor: '#22C55E',
        alignItems: 'center',
        justifyContent: 'center',
    },
    puntoNumero: { fontSize: 11, fontWeight: '700', color: 'white' },
    puntoCoordenadas: { fontSize: 12, color: T.text.secondary, flex: 1 },
    botonLimpiar: { marginTop: 8, alignSelf: 'flex-start' },
    textoLimpiar: { fontSize: 12, color: '#ef4444' }, // corregido
    botonesNavegacion: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 4,
        gap: 12,
    },
    botonAtras: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: T.input.border,
        flex: 1,
        justifyContent: 'center',
    },
    textoAtras: { color: T.text.secondary, fontWeight: '600', fontSize: 14 },
    botonSiguiente: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#22C55E',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
        flex: 1,
        justifyContent: 'center',
    },
    textoSiguiente: { color: 'white', fontWeight: '700', fontSize: 14 },
    botonGuardar: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#16a34a',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
        flex: 1,
        justifyContent: 'center',
    },
    textoGuardar: { color: 'white', fontWeight: '700', fontSize: 14 },
});