name: Create Production Builds

# Se dispara automáticamente se hace un push en la rama main en GitGub
on:
  push:
    branches: ["main"]

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
  build_ios:
    type: build
    params:
      platform: ios
      profile: production
