// MapaColaboradores.styles.js
import { StyleSheet } from "react-native";
import theme from "../../../constants/theme";

export const styles = StyleSheet.create({
    contenedor: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    textoCarga: {
        marginTop: 12,
        fontSize: theme.lightMode.tipografia.fontSize.card,
        fontFamily: theme.lightMode.tipografia.fonts.regular,
    },
    mapaContenedor: {
        flex: 1,
    },
    mapaWrapper: {
        flex: 1,
        position: 'relative',
    },
    headerInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
    },
    botonesContainer: {
        flexDirection: 'row',
        gap: 8,
    },
    gruposTexto: {
        fontSize: theme.lightMode.tipografia.fontSize.card,
        fontFamily: theme.lightMode.tipografia.fonts.regular,
    },
    botonCrearRuta: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: theme.lightMode.Button.primary.borderRadius,
    },
    botonRutaOptima: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: theme.lightMode.Button.primary.borderRadius,
        borderWidth: 1,
    },
    textoBotonCrear: {
        fontSize: theme.lightMode.tipografia.fontSize.card,
        fontFamily: theme.lightMode.tipografia.fonts.medium,
    },
    panelCrearRuta: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        borderTopWidth: 1,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
    },
    panelHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    panelTitulo: {
        fontSize: theme.lightMode.tipografia.fontSize.title,
        fontFamily: theme.lightMode.tipografia.fonts.bold,
    },
    cerrarPanel: {
        fontSize: 20,
        fontWeight: 'bold',
        padding: 4,
    },
    inputContainer: {
        gap: 12,
        marginBottom: 20,
    },
    input: {
        height: 48,
        borderWidth: 1,
        borderRadius: theme.lightMode.input.borderRadius,
        paddingHorizontal: 12,
        fontSize: theme.lightMode.tipografia.fontSize.input,
        fontFamily: theme.lightMode.tipografia.fonts.regular,
    },
    botonGuardar: {
        paddingVertical: 12,
        borderRadius: theme.lightMode.Button.primary.borderRadius,
        alignItems: 'center',
        marginTop: 12,
    },
    textoGuardar: {
        fontSize: theme.lightMode.tipografia.fontSize.card,
        fontFamily: theme.lightMode.tipografia.fonts.bold,
    },
    botonLimpiar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        marginVertical: 8,
        borderRadius: 8,
        backgroundColor: '#FEE2E2',
    },
    textoLimpiar: {
        color: '#DC2626',
        fontSize: 14,
        fontWeight: '500',
    },
    puntoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 4,
    },
    iconoBasura: {
        color: 'red',
        fontSize: 16,
    },
    iconoUbicacion: {
        color: 'red',
        fontSize: 16,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingText: {
        color: 'white',
        fontSize: 16,
        marginTop: 10,
        fontWeight: 'bold',
    },
    botonMostrarPanel: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: theme.lightMode.Button.primary.background,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 30,
        zIndex: 1000,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 5,
    },
    textoMostrarPanel: {
        color: theme.lightMode.Button.primary.Text,
        fontWeight: 'bold',
        fontSize: 14,
    },
    botonesFlotantes: {
        position: 'absolute',
        top: 16,
        left: 16,
        right: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
        zIndex: 1000,
    },
    botonFlotanteCrear: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 5,
    },
    botonFlotanteOptima: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 5,
    },
});