name: Expo Build - Android APK

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

env:
  NODE_VERSION: "24"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm install

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # --output para descargar el APK al servidor de GITHUB
      - name: Build Android APK
        run: eas build --platform android --profile preview --wait --output=./build-sintrap.apk

      - name: Upload APK to artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          # Se apunta al archivo exapto que descargamos
          path: frontend/build-sintrap.apk
          retention-days: 30
